language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - tests/install_sodium.sh
  - pip install -q "file://$PWD#egg=pynacl[tests]"
script:
  - pep8 nacl
  - pylint --rcfile .pylintrc -r y nacl
  - py.test
