language: python
python: 2.7
env:
  - TOXENV=py26 SODIUM_INSTALL=bundled CC=gcc
  - TOXENV=py27 SODIUM_INSTALL=bundled CC=gcc
  - TOXENV=py32 SODIUM_INSTALL=bundled CC=gcc
  - TOXENV=py33 SODIUM_INSTALL=bundled CC=gcc
  - TOXENV=py34 SODIUM_INSTALL=bundled CC=gcc
  - TOXENV=pypy SODIUM_INSTALL=bundled CC=gcc
  - TOXENV=py26 SODIUM_INSTALL=system CC=gcc
  - TOXENV=py27 SODIUM_INSTALL=system CC=gcc
  - TOXENV=py32 SODIUM_INSTALL=system CC=gcc
  - TOXENV=py33 SODIUM_INSTALL=system CC=gcc
  - TOXENV=py34 SODIUM_INSTALL=system CC=gcc
  - TOXENV=pypy SODIUM_INSTALL=system CC=gcc
  - TOXENV=py26 SODIUM_INSTALL=bundled CC=clang
  - TOXENV=py27 SODIUM_INSTALL=bundled CC=clang
  - TOXENV=py32 SODIUM_INSTALL=bundled CC=clang
  - TOXENV=py33 SODIUM_INSTALL=bundled CC=clang
  - TOXENV=py34 SODIUM_INSTALL=bundled CC=clang
  - TOXENV=pypy SODIUM_INSTALL=bundled CC=clang
  - TOXENV=py26 SODIUM_INSTALL=system CC=clang
  - TOXENV=py27 SODIUM_INSTALL=system CC=clang
  - TOXENV=py32 SODIUM_INSTALL=system CC=clang
  - TOXENV=py33 SODIUM_INSTALL=system CC=clang
  - TOXENV=py34 SODIUM_INSTALL=system CC=clang
  - TOXENV=pypy SODIUM_INSTALL=system CC=clang
  - TOXENV=docs
  - TOXENV=meta

install:
  # Install Sodium if we need too
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then tar zxvf LATEST.tar.gz; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then cd libsodium-*; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then ./configure; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then make; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then make check; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then sudo make install; fi"
  - "if [[ $SODIUM_INSTALL == 'system' ]]; then sudo ldconfig; fi"

  # Install tox and coveralls so we can run our tests
  - pip install tox coveralls


script:
  - tox

after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#cryptography-dev"
    use_notice: true
    skip_join: true
