language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  # - "pypy"  # Travis only has PyPy 1.9, cffi requires 2.0 (Unreleased)
install:
  - sudo apt-get install python-pip
  - sudo /usr/bin/pip install git+git://github.com/pyinvoke/invoke.git
  - invoke install-nacl --library=$NACL
  - invoke install --dev
script:
  - invoke tests
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - LD_RUN_PATH=/usr/local/lib
  matrix:
    - NACL=libsodium
    - NACL=nacl
matrix:
  exclude:
    - python: "2.6"
      env:
        - NACL=nacl
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
    - python: "3.2"
      env:
        - NACL=nacl
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
    - python: "3.3"
      env:
        - NACL=nacl
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
    - python: "pypy"
      env:
        - NACL=nacl
        - LD_LIBRARY_PATH=/usr/local/lib
        - LD_RUN_PATH=/usr/local/lib
